// 需要增加新的 Icon 需要來這裡添加
import {
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  Building2,
  Landmark,
  CircleDollarSign,
  HandCoins,
  Receipt,
  TrendingUp,
  Utensils,
  Coffee,
  UtensilsCrossed,
  Cookie,
  CupSoda,
  Wine,
  Apple,
  Car,
  Bus,
  Train,
  CarTaxiFront,
  TrainFront,
  Fuel,
  ParkingCircle,
  Ticket,
  Wrench,
  Gamepad2,
  Film,
  PartyPopper,
  Plane,
  Music,
  ShoppingBag,
  Shirt,
  Smartphone,
  ShoppingBasket,
  Sparkles,
  User,
  Scissors,
  SprayCan,
  Dumbbell,
  Stethoscope,
  Pill,
  ShieldCheck,
  Home,
  Zap,
  Wifi,
  Users,
  Baby,
  PawPrint,
  HeartHandshake,
  Phone,
  GraduationCap,
  Book,
  Presentation,
  School,
  Gift,
  RefreshCcw,
  Percent,
  MoreHorizontal,
  Heart,
  FileText,
  ArrowRightLeft,
  ArrowUpFromLine,
  ArrowDownToLine,
  Undo2,
  RefreshCw,
  CircleHelp,
  Tag,
} from 'lucide-react';

// DB 值: Icon 值
// 帳戶與分類共用的 Icons (小寫 key)
export const ACCOUNT_ICONS = {
  wallet: Wallet,
  'credit-card': CreditCard,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  building: Building2,
  landmark: Landmark,
  dollar: CircleDollarSign,
  coins: HandCoins,
  receipt: Receipt,
  trending: TrendingUp,
  utensils: Utensils,
  coffee: Coffee,
  'utensils-crossed': UtensilsCrossed,
  cookie: Cookie,
  wine: Wine,
  car: Car,
  bus: Bus,
  train: Train,
  fuel: Fuel,
  home: Home,
  shopping: ShoppingBag,
  shirt: Shirt,
  phone: Smartphone,
  basket: ShoppingBasket,
  user: User,
  pill: Pill,
  heart: Heart,
  gift: Gift,
  music: Music,
  film: Film,
  gamepad: Gamepad2,
  plane: Plane,
  school: School,
  book: Book,
  baby: Baby,
  paw: PawPrint,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  file: FileText,
  help: CircleHelp,
  tag: Tag,
} as const;

export const CATEGORY_ICONS_MAP = {
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  Utensils,
  Coffee,
  UtensilsCrossed,
  Cookie,
  CupSoda,
  Wine,
  Apple,
  Car,
  Bus,
  Train,
  CarTaxiFront,
  TrainFront,
  Fuel,
  ParkingCircle,
  Ticket,
  Wrench,
  Gamepad2,
  Film,
  PartyPopper,
  Plane,
  Music,
  ShoppingBag,
  Shirt,
  Smartphone,
  ShoppingBasket,
  Sparkles,
  User,
  Scissors,
  SprayCan,
  Dumbbell,
  Stethoscope,
  Pill,
  ShieldCheck,
  Home,
  Zap,
  Wifi,
  Users,
  Baby,
  PawPrint,
  HeartHandshake,
  Phone,
  GraduationCap,
  Book,
  Presentation,
  School,
  Gift,
  TrendingUp,
  RefreshCcw,
  Percent,
  MoreHorizontal,
  Heart,
  FileText,
  Receipt,
  ArrowRightLeft,
  ArrowUpFromLine,
  ArrowDownToLine,
  Undo2,
  RefreshCw,
} as const;

export type IconName = keyof typeof ACCOUNT_ICONS;

// 為什麼要分兩個？因為當初設計值把 account 都塞入連字號的寫法了...
export const getIcon = (name: string | null | undefined) => {
  if (!name) return CircleHelp;

  if (name in CATEGORY_ICONS_MAP) {
    return CATEGORY_ICONS_MAP[name as keyof typeof CATEGORY_ICONS_MAP];
  }

  if (name in ACCOUNT_ICONS) {
    return ACCOUNT_ICONS[name as IconName];
  }

  return CircleHelp;
};
